# Generated by Django 4.2.19 on 2025-02-27 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='screening_status',
            field=models.CharField(choices=[('Not Screened', 'Not Screened'), ('Qualified - RM', 'Qualified - RM'), ('Qualified - DM', 'Qualified - DM'), ('Qualified - TL', 'Qualified - TL'), ('Qualified - SRSW', 'Qualified - SRSW'), ('Qualified - RSW', 'Qualified - RSW'), ('Unqualified', 'Unqualified'), ('Unqualified - Out of country', 'Unqualified - Out of country'), ('Unqualified - NSFW', 'Unqualified - NSFW')], default='Not Screened'),
        ),
    ]
