# Generated by Django 5.1.7 on 2025-03-09 20:54

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_candidate_screening_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='location',
            new_name='address',
        ),
        migrations.AddField(
            model_name='candidate',
            name='geolocation',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='job',
            name='geolocation',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='job',
            name='postcode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='availability',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['postcode'], name='idx_candidate_postcode'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(condition=models.Q(('geolocation__isnull', False)), fields=['geolocation'], name='idx_candidate_geolocation'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['job_title'], name='idx_job_title'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['address'], name='idx_job_address'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['postcode'], name='idx_job_postcode'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(condition=models.Q(('geolocation__isnull', False)), fields=['geolocation'], name='idx_job_geolocation'),
        ),
    ]
