# Generated by Django 5.1.7 on 2025-03-09 22:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_rename_location_job_address_candidate_geolocation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='experience',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, default=list, null=True, size=None),
        ),
    ]
