# Generated by Django 5.1.7 on 2025-03-16 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_candidate_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='screening_status',
            field=models.CharField(choices=[('Not Screened', 'Not Screened'), ('Qualified - RM', 'Qualified - RM'), ('Qualified - DM', 'Qualified - DM'), ('Qualified - TL', 'Qualified - TL'), ('Qualified - SRSW', 'Qualified - SRSW'), ('Qualified - RSW', 'Qualified - RSW'), ('Intermediate', 'Intermediate'), ('Unqualified', 'Unqualified'), ('Unqualified - Out of country', 'Unqualified - Out of country'), ('Unqualified - NSFW', 'Unqualified - NSFW')], default='Not Screened'),
        ),
    ]
